mapping_type: "rdf"
version: "1.0"
scenario_name: rdf_card_games
database: "card_games"
ttl_path: "card_games.ttl"
databases:
  card_games: "sqlite:///../MINIDEV_sqlite/dev_databases/card_games/card_games.sqlite"
